# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-fasthtml-file-browser',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-fasthtml-file-browser',
                'lib_path': 'cjm_fasthtml_file_browser'},
  'syms': {}}
