"""Main file browser component with virtualized collection rendering."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/browser.ipynb.

# %% auto #0
__all__ = ['render_file_browser']

# %% ../../nbs/components/browser.ipynb #c3d4e5f6
from typing import Any, Callable, Optional

from fasthtml.common import Div, Script

# DaisyUI components
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, border_dui
from cjm_fasthtml_daisyui.utilities.border_radius import border_radius

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.sizing import w, h
from cjm_fasthtml_tailwind.utilities.borders import border
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, flex_direction, grow
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.core.base import combine_classes

# Virtual collection
from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState, VirtualCollectionUrls,
)
from cjm_fasthtml_virtual_collection.core.html_ids import VirtualCollectionHtmlIds
from cjm_fasthtml_virtual_collection.core.button_ids import VirtualCollectionButtonIds
from cjm_fasthtml_virtual_collection.components.collection import render_virtual_collection
from cjm_fasthtml_virtual_collection.keyboard.actions import (
    create_collection_focus_zone, create_collection_nav_actions,
    build_collection_url_map, apply_nav_sync,
)
from cjm_fasthtml_virtual_collection.js.scroll import generate_scroll_nav_js
from cjm_fasthtml_virtual_collection.js.touch import generate_touch_nav_js
from cjm_fasthtml_virtual_collection.js.scrollbar import generate_scrollbar_js
from cjm_fasthtml_virtual_collection.js.auto_fit import generate_auto_fit_js, auto_fit_callback_name

from cjm_fasthtml_keyboard_navigation.core.manager import ZoneManager
from cjm_fasthtml_keyboard_navigation.components.system import render_keyboard_system

from cjm_fasthtml_viewport_fit.models import ViewportFitConfig
from cjm_fasthtml_viewport_fit.components import render_viewport_fit_script

# Local imports
from ..core.config import FileBrowserConfig
from ..core.models import DirectoryListing, BrowserState
from ..core.html_ids import FileBrowserHtmlIds
from .path_bar import render_path_bar
from .item import render_empty_state

# %% ../../nbs/components/browser.ipynb #h8c9d0e1
def render_file_browser(
    items: list,                                # Current filtered/sorted FileInfo list
    config: FileBrowserConfig,                  # Browser configuration
    state: BrowserState,                        # Browser state (path, selection)
    listing: DirectoryListing,                  # Raw directory listing (for path bar)
    vc_config: VirtualCollectionConfig,         # Virtual collection config
    vc_state: VirtualCollectionState,           # Virtual collection state
    vc_ids: VirtualCollectionHtmlIds,           # Virtual collection HTML IDs
    vc_btn_ids: VirtualCollectionButtonIds,     # Virtual collection button IDs
    urls: VirtualCollectionUrls,                # Virtual collection URL bundle
    render_cell: Callable,                      # Cell render callback
    navigate_url: str,                          # URL for directory navigation
    refresh_url: str,                           # URL for refresh
    path_input_url: str = "",                   # URL for path input (optional)
    home_path: str = "",                        # Home directory path
    hx_target: Optional[str] = None,            # Override HTMX target (default: container_id)
) -> Any:  # Complete file browser component
    """Render the complete file browser with virtualized collection."""
    ids = FileBrowserHtmlIds()
    target = hx_target or FileBrowserHtmlIds.as_selector(config.container_id)

    children = []

    # Path bar
    if config.show_path_bar:
        children.append(render_path_bar(
            current_path=listing.path,
            parent_path=listing.parent_path,
            home_path=home_path or state.current_path,
            config=config,
            navigate_url=navigate_url,
            refresh_url=refresh_url,
            hx_target=target,
            path_bar_id=ids.PATH_BAR,
        ))

    # Virtual collection (wrapped in flex column so collection fills available height)
    children.append(Div(
        render_virtual_collection(
            items=items,
            config=vc_config,
            state=vc_state,
            ids=vc_ids,
            urls=urls,
            render_cell=render_cell,
            render_empty=render_empty_state,
        ),
        id=config.content_id,
        cls=combine_classes(
            grow(), overflow.hidden,
            flex_display, flex_direction.col,
        ),
    ))

    # Keyboard system
    zone = create_collection_focus_zone(vc_ids)
    nav_actions = create_collection_nav_actions(zone.id, vc_btn_ids)
    manager = ZoneManager(zones=(zone,), actions=nav_actions)
    url_map = build_collection_url_map(vc_btn_ids, urls)
    target_map = {btn_id: f"#{vc_ids.rows}" for btn_id in url_map}
    swap_map = {btn_id: "none" for btn_id in url_map}

    # Activate button needs outerHTML swap targeting the browser container,
    # because on_activate may return a full browser re-render (directory navigation).
    # OOB elements from file selection still work with outerHTML swap.
    container_selector = f"#{config.container_id}"
    target_map[vc_btn_ids.activate] = container_selector
    swap_map[vc_btn_ids.activate] = "outerHTML"

    kb_system = render_keyboard_system(manager, url_map=url_map, target_map=target_map, swap_map=swap_map)
    apply_nav_sync(kb_system, vc_ids)

    children.append(kb_system.script)
    children.append(kb_system.hidden_inputs)
    children.append(kb_system.action_buttons)

    # JS scripts
    children.append(Script(generate_scroll_nav_js(vc_ids, vc_btn_ids)))
    children.append(Script(generate_touch_nav_js(vc_ids, vc_btn_ids, urls)))
    children.append(Script(generate_scrollbar_js(vc_ids, urls)))
    children.append(Script(generate_auto_fit_js(
        vc_ids, vc_config, urls,
        total_items=len(items),
        initial_visible=vc_state.visible_rows,
    )))
    children.append(render_viewport_fit_script(ViewportFitConfig(
        namespace=vc_config.prefix,
        target_id=vc_ids.wrapper,
        container_id=config.content_id,
        resize_callback=auto_fit_callback_name(vc_config),
        enable_htmx_settle=False,
    )))

    return Div(
        *children,
        id=config.container_id,
        cls=combine_classes(
            flex_display, flex_direction.col,
            w.full, h.full,
            border(), border_dui.base_300, border_radius.box,
            bg_dui.base_100,
            overflow.hidden
        )
    )
