"""Main file browser component that composes all sub-components."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/browser.ipynb.

# %% auto #0
__all__ = ['render_file_browser', 'render_browser_content', 'generate_scroll_preservation_script']

# %% ../../nbs/components/browser.ipynb #c3d4e5f6
from typing import Any, Optional

from fasthtml.common import Div

# DaisyUI components
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, border_dui
from cjm_fasthtml_daisyui.utilities.border_radius import border_radius

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.sizing import w, h, min_h
from cjm_fasthtml_tailwind.utilities.borders import border
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, flex_direction, grow
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.core.base import combine_classes

# Local imports
from ..core.config import FileBrowserConfig
from ..core.models import DirectoryListing, BrowserState
from ..core.html_ids import FileBrowserHtmlIds
from .path_bar import render_path_bar
from .toolbar import render_toolbar
from .listing import render_listing

# %% ../../nbs/components/browser.ipynb #h8c9d0e1
def render_file_browser(
    listing: DirectoryListing,              # Current directory listing
    config: FileBrowserConfig,              # Browser configuration
    state: BrowserState,                    # Current browser state
    navigate_url: str,                      # URL for directory navigation
    select_url: str,                        # URL for file selection
    toggle_view_url: str,                   # URL for view mode toggle
    change_sort_url: str,                   # URL for sort change
    refresh_url: str,                       # URL for refresh
    path_input_url: str = "",               # URL for path input (optional)
    home_path: str = "",                    # Home directory path
    hx_target: Optional[str] = None,        # Override HTMX target (default: container_id)
    select_hx_target: Optional[str] = None, # Override select target (default: content_id)
    select_hx_swap: Optional[str] = None,   # Override select swap (default: "outerHTML")
) -> Any:  # Complete file browser component
    """
    Render the complete file browser component.
    
    Select operations target the content wrapper (not the full container) so that
    path bar and toolbar are preserved. Consuming apps should include a scroll
    preservation script for the content wrapper to maintain scroll position on select.
    
    Component hierarchy:
    ```
    render_file_browser(listing, config, state, ...)
    ├── render_path_bar(...)        [if config.show_path_bar]
    │   ├── nav_buttons()
    │   └── breadcrumbs() OR path_input()
    ├── render_toolbar(...)         [if config.show_toolbar]
    │   ├── view_mode_toggle()
    │   └── sort_controls()
    └── render_listing(...)
        ├── parent_navigation()
        └── items[]
            └── render_item() [file or folder]
    ```
    """
    ids = FileBrowserHtmlIds()
    # Use provided hx_target or default to container_id
    target = hx_target or FileBrowserHtmlIds.as_selector(config.container_id)
    # Select operations target the content wrapper (preserves path bar + toolbar)
    _select_target = select_hx_target or FileBrowserHtmlIds.as_selector(config.content_id)
    _select_swap = select_hx_swap or "outerHTML"
    
    children = []
    
    # Path bar
    if config.show_path_bar:
        children.append(render_path_bar(
            current_path=listing.path,
            parent_path=listing.parent_path,
            home_path=home_path or state.current_path,
            config=config,
            navigate_url=navigate_url,
            refresh_url=refresh_url,
            hx_target=target,
            path_bar_id=ids.PATH_BAR,
        ))
    
    # Toolbar
    if config.show_toolbar:
        children.append(render_toolbar(
            state=state,
            config=config,
            toggle_url=toggle_view_url,
            sort_url=change_sort_url,
            hx_target=target,
            toolbar_id=ids.TOOLBAR,
        ))
    
    # Directory listing
    listing_content = render_listing(
        listing=listing,
        config=config,
        state=state,
        navigate_url=navigate_url,
        select_url=select_url,
        hx_target=target,
        listing_id=ids.LISTING,
        select_hx_target=_select_target,
        select_hx_swap=_select_swap,
    )
    
    # Wrap listing in scrollable container (use config.content_id)
    children.append(Div(
        listing_content,
        id=config.content_id,
        cls=combine_classes(grow(), overflow.auto, min_h(48))
    ))
    
    # Build main container
    return Div(
        *children,
        id=config.container_id,
        cls=combine_classes(
            flex_display, flex_direction.col,
            w.full, h.full,
            border(), border_dui.base_300, border_radius.box,
            bg_dui.base_100,
            overflow.hidden
        )
    )

# %% ../../nbs/components/browser.ipynb #l2g3h4i5
def render_browser_content(
    listing: DirectoryListing,              # Current directory listing
    config: FileBrowserConfig,              # Browser configuration
    state: BrowserState,                    # Current browser state
    navigate_url: str,                      # URL for directory navigation
    select_url: str,                        # URL for file selection
    hx_target: Optional[str] = None,        # Override HTMX target (default: container_id)
    select_hx_target: Optional[str] = None, # Override select target (default: content_id)
    select_hx_swap: Optional[str] = None,   # Override select swap (default: "outerHTML")
) -> Any:  # Content wrapper with listing (for outerHTML swap on content_id)
    """Render the content wrapper with listing for select-triggered HTMX updates.
    
    Returns the scrollable content wrapper div (with its ID) containing the listing.
    Used as the outerHTML replacement for the content wrapper element, preserving
    path bar and toolbar while replacing only the scrollable listing area.
    """
    ids = FileBrowserHtmlIds()
    target = hx_target or FileBrowserHtmlIds.as_selector(config.container_id)
    _select_target = select_hx_target or FileBrowserHtmlIds.as_selector(config.content_id)
    _select_swap = select_hx_swap or "outerHTML"
    
    listing_content = render_listing(
        listing=listing,
        config=config,
        state=state,
        navigate_url=navigate_url,
        select_url=select_url,
        hx_target=target,
        listing_id=ids.LISTING,
        select_hx_target=_select_target,
        select_hx_swap=_select_swap,
    )
    
    return Div(
        listing_content,
        id=config.content_id,
        cls=combine_classes(grow(), overflow.auto, min_h(48))
    )

# %% ../../nbs/components/browser.ipynb #euhdxhy65os
def generate_scroll_preservation_script(
    content_id: str,  # HTML ID of the scrollable content wrapper
) -> str:  # JavaScript snippet for scroll preservation
    """Generate a JS snippet that preserves scroll position on outerHTML swaps.
    
    Include this script on the page (e.g., via `Script(generate_scroll_preservation_script(...))`).
    It listens for HTMX swap events targeting the content wrapper and saves/restores scrollTop.
    """
    return f"""(function() {{
    var saved = null;
    document.addEventListener('htmx:beforeSwap', function(e) {{
        if (e.detail.target && e.detail.target.id === '{content_id}') {{
            saved = e.detail.target.scrollTop;
        }}
    }});
    document.addEventListener('htmx:afterSwap', function(e) {{
        if (saved != null) {{
            var el = document.getElementById('{content_id}');
            if (el) {{ requestAnimationFrame(function() {{ el.scrollTop = saved; saved = null; }}); }}
        }}
    }});
}})();"""
