"""Sorting and filtering utilities for file listings."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/utils.ipynb.

# %% auto #0
__all__ = ['sort_files', 'filter_files']

# %% ../../nbs/components/utils.ipynb #c3d4e5f6
from typing import List

from cjm_file_discovery.core.models import FileInfo
from ..core.config import FilterConfig

# %% ../../nbs/components/utils.ipynb #e5f6a7b8
def sort_files(
    files: List[FileInfo],           # Files to sort
    sort_by: str = "name",           # Sort field
    descending: bool = False,        # Sort direction
    folders_first: bool = True       # Sort folders before files
) -> List[FileInfo]:  # Sorted file list
    """Sort files by the specified field."""
    def sort_key(f: FileInfo):
        # Primary: folders first (if enabled)
        folder_order = 0 if f.is_directory else 1 if folders_first else 0
        
        # Secondary: sort field
        if sort_by == "name":
            value = f.name.lower()
        elif sort_by == "size":
            value = f.size or 0
        elif sort_by == "modified":
            value = f.modified or 0
        elif sort_by == "type":
            value = f.extension.lower() if f.extension else ""
        else:
            value = f.name.lower()
        
        return (folder_order, value)
    
    return sorted(files, key=sort_key, reverse=descending)


def filter_files(
    files: List[FileInfo],           # Files to filter
    filter_config: FilterConfig      # Filter configuration
) -> List[FileInfo]:  # Filtered file list
    """Filter files based on configuration."""
    return [f for f in files if filter_config.matches(f)]
